import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// UI Provider
import { ChakraUIProviders } from "./ChakraUIProviders";

// Global Components
import Nav from "@/components/global/nav";
import Footer from "@/components/global/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraUIProviders>
          <Nav />
          {children}
          <Footer />
        </ChakraUIProviders>
      </body>
    </html>
  );
}
